# Publish GitHub Workflow Artifacts Tutorial Beispielname : 
Publish GitHub Actions Artifacts Example
 
on : 
push : 
Branches : [ main ]
 
jobs :
        
archive-build-artifacts : running 
-on : ubuntu-latest 


     
run : mkdir wsapackage
        


    
  
uses :  actions /upload-artifact  
with : 
name : WSAwithGapps_fromWZ_2205.40000.14.0_nightly 
path : wsapackage
