name: 'Upload a Build Artifact'
on:
description: 'Upload a build artifact that can be used by subsequent workflow steps'
author: 'GitHub'
inputs: 
  name:
    description: 'WSAwithGapps_fromWZ_2205.40000.14.0_nightly'
    default: 'artifact'
  path: C:\Users\zafir\Documents\GitHub\WSAGapps-Build\wsapackage
  description: WSABuild
    required: true
  if-no-files-found:
  
    default: 'warn'
  retention-days: 90
   
runs:
  using: 'node16'
  main: 'dist/index.js'
