name: 'Upload a Build Artifact'
description: 'Upload a build artifact that can be used by subsequent workflow steps'
author: 'GitHub'
inputs: 
  name:
    description: 'WSAwithGapps_fromWZ_2205.40000.14.0_nightly'
    default: 'artifact'
  path: C:\Users\zafir\Documents\GitHub\WSAGapps-Build\wsapackage
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
  if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'
  retention-days: 90
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.
runs:
  using: 'node16'
  main: 'dist/index.js'
